version: '3.8'

services:
  app:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - .:/app
    env_file:
      - ".env"
    environment:
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
